dist: bionic
sudo: required

language: java
jdk:
  - openjdk11

notifications:
  email:
    - acogoluegnes@pivotal.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - esl-erlang=1:22.1.1-1
branches:
  only:
    - master
before_script:
  - ./bin/before_build.sh

script: ./mvnw clean verify -Drabbitmqctl.bin='rabbitmq/sbin/rabbitmqctl'
cache:
  directories:
    - $HOME/.m2
install: true

