name: Publish documentation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Generate documentation
        run: |
          rm -rf target/generated-docs
          make doc
      - name: Publish documentation to GitHub Pages
        run: |
          git config user.name "rabbitmq-ci"
          git config user.email "rabbitmq-ci@users.noreply.github.com"
          ci/publish-documentation-to-github-pages.sh
      - name: Prepare worker
        run: |
          mkdir ci/worker/public
          cp target/generated-docs/index.html ci/worker/public
      - name: Publish documentation to Cloudflare
        uses: cloudflare/wrangler-action@v3.1.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm i -D @cloudflare/kv-asset-handler
          command: deploy --name perftest-dev --route https://perftest-dev.rabbitmq.com/*
          workingDirectory: 'ci/worker'
