name: Build (Linux)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test
        run: ./mvnw check -Drabbitmqctl.bin=DOCKER:${{job.services.rabbitmq.id}}