name: Test against supported Java versions

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        version: [ '8', '11', '17', '21', '24', '25-ea' ]
    name:  Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v5
      - name: Checkout tls-gen
        uses: actions/checkout@v5
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Display Java version
        run: ./mvnw --version
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq --no-transfer-progress \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
