name: Test against RabbitMQ stable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - name: Checkout tls-gen
        uses: actions/checkout@v5
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Start broker
        run: ci/start-broker.sh
      - name: Test
        run: ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq --no-transfer-progress
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
      - name: Publish snapshot
        run: ./mvnw clean deploy -DskipITs -DskipTests --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Package Perf Test
        run: ci/package-perf-test.sh
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Delete old releases
        uses: docker://rabbitmqdevenv/delete-release-action:latest
        with:
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          tag-filter: '^v-rabbitmq-perf-test-.*-[0-9]{8}-[0-9]{6}$'
          keep-last-n: 2
      - name: Push to GitHub Release
        uses: softprops/action-gh-release@v2.3.4
        with:
          files: packages/*
          name: ${{ env.release_name }}
          tag_name: ${{ env.tag_name }}
          target_commitish: main
          prerelease: true
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
      - name: Delete latest release
        uses: docker://rabbitmqdevenv/delete-release-action:latest
        with:
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          tag-filter: '^v-rabbitmq-perf-test-latest$'
          keep-last-n: 0
      - name: Make sure latest release is deleted
        run: |
          sleep 5s
      - name: Push to GitHub Release
        uses: softprops/action-gh-release@v2.3.4
        with:
          files: packages-latest/*
          name: rabbitmq-perf-test-latest
          tag_name: v-rabbitmq-perf-test-latest
          target_commitish: main
          prerelease: true
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          repository: rabbitmq/rabbitmq-java-tools-binaries-dev
      - name: Trigger Perf Test Docker image build
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: new_snapshot
          client-payload: >-
            {"archive_url" : "https://github.com/rabbitmq/rabbitmq-java-tools-binaries-dev/releases/download/${{ env.tag_name }}/perf-test-${{ env.release_version}}.jar",
             "tags": "pivotalrabbitmq/perf-test:dev,pivotalrabbitmq/perf-test:dev-${{ env.release_version }}"}
      - name: Generate documentation
        run: |
          rm -rf target/generated-docs
          make doc
      - name: Commit documentation changes
        run: |
          git config user.name "rabbitmq-ci"
          git config user.email "rabbitmq-ci@users.noreply.github.com"
          ci/commit-documentation.sh
