name: Test against RabbitMQ stable (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - '!src/docs/**'
      - pom.xml
      - ci/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - name: Checkout tls-gen
        uses: actions/checkout@v5
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Test
        run: ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq --no-transfer-progress
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
