name: Test against supported Java versions

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  RABBITMQ_IMAGE: 'rabbitmq:3.11'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '8', '11', '17', '20', '21-ea' ]
    name:  Test against Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq --no-transfer-progress \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
